version: '3'

services:
  web:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - ./.env

  db:
    image: postgres:13.0-alpine
    volumes:
      - data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=jaspercyan
      - POSTGRES_USER=postgres
      - POSTGRES_DB=notesdatabase
    ports:
      - 5432:5432

  nginx:
    build: ./nginx
    volumes:
    - static:/static
    ports:
    - 80:80
    # - 443:443
    depends_on:
      - prometheus
      - web

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
    ports:
      - 9090:9090
    depends_on:
      - web
      - cadvisor
  
  grafana:
    image: grafana/grafana
    environment:
      GF_INSTALL_PLUGINS: "grafana-clock-panel,grafana-simple-json-datasource"
    restart: 'no'
    volumes:
      - grafana:/var/lib/grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    
  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

volumes:
  data:
  static:
  grafana: