version: '3'

services:
  web:
    build: .
    # command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - ./.env

  db:
    image: postgres:13.0-alpine
    volumes:
      - data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=jaspercyan
      - POSTGRES_USER=postgres
      - POSTGRES_DB=notesdatabase
    ports:
      - 5432:5432

  nginx:
    build: ./nginx
    volumes:
    - static:/static
    ports:
    - 80:80
    - 443:443
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
    ports:
      - 9090:9090
    depends_on:
      - web

volumes:
  data:
  static: