version: '3'

services:
  web:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - ./.env

  db:
    image: postgres:13.0-alpine
    volumes:
      - data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=jaspercyan
      - POSTGRES_USER=postgres
      - POSTGRES_DB=notesdatabase
    ports:
      - 5432:5432

  nginx:
    build: ./nginx
    restart: always
    volumes:
    - ./public_html:/public_html
    - ./nginx:/etc/nginx/conf.d
    - ./dhparam:/etc/nginx/dhparam
    - ./certbot/conf:/etc/nginx/ssl
    - ./certbot/data:/usr/share/nginx/html/letsencrypt
    ports:
    - 80:80
    - 443:443
    depends_on:
      - prometheus
      - web

  certbot:
    image: certbot/certbot:latest
    command: certonly --webroot --webroot-path=/usr/share/nginx/html/letsencrypt --email rahulranjan25.RR@gmail.com --agree-tos --no-eff-email -d rahul-api.sr.flipr.ai -d rahul-prometheus.sr.flipr.ai -d rahul-grafana.sr.flipr.ai -d rahul-cadvisor.sr.flipr.ai -d rahul-node.sr.flipr.ai
    volumes:
    - ./certbot/conf:/etc/letsencrypt
    - ./certbot/logs:/var/log/letsencrypt
    - ./certbot/data:/usr/share/nginx/html/letsencrypt

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
    ports:
      - 9090:9090
    depends_on:
      - web
      - cadvisor
  
  grafana:
    image: grafana/grafana
    environment:
      GF_INSTALL_PLUGINS: "grafana-clock-panel,grafana-simple-json-datasource"
    restart: 'no'
    volumes:
      - grafana:/var/lib/grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    
  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
  
  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /:/host:ro,rslave
    command: 
      - '--path.rootfs=/host'
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - 9100:9100
  
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    ports:
      - 8081:8080
    volumes:
      - jenkins:/var/jenkins_home

volumes:
  data:
  static:
  grafana:
  jenkins:
