# Generated by Django 4.1.4 on 2022-12-30 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_note_options_note_updated"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="note",
            options={},
        ),
    ]
