global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'web_monitoring'
    metrics_path: /metrics
    static_configs:
      - targets:
        - web:8000
  
  - job_name: cadvisor
    metrics_path: /cadvisor-metrics
    scrape_interval: 5s
    static_configs:
      - targets:
        - cadvisor:8080
